### ISSUE TITLE
13 May Review

### ISSUE THREAD

**Issue by simandebvu** [wrakc/apple-clone#1]
😄 Great Project just a few things to address

- Input must not be between anchor tags 
- Use __ul__ in the nav links
- Max Width for container
- Use aside instead of div
- The transition for input search in the navbar should be implemented.
- Check spellings in the header 😉

**Comment by carlosveigadev** [comment]
Thanks guys, here are the changes:
- Input must not be between anchor tags :heavy_check_mark: 
- Use __ul__ in the nav links  :heavy_check_mark: 
- Max Width for container  :heavy_check_mark: 
- Use aside instead of div  :heavy_check_mark: 
- The transition for input search in the navbar should be implemented.  :heavy_check_mark: 
- Check spellings in the header wink  :heavy_check_mark: 

Thanks a lot!
